	<footer>
		
		<div class="layoutFooter">
			
			<img class="logoPetit" src="./images/V4.svg" alt="Les Loups">
			<p>Réalisation : <a href="">Jean Annaix</a>. <br><strong>Ce site est un projet d'étudiant.</strong><br>L'équipe des Loups de Sakami est totalement fictive.<br>Toute ressemblance avec des clubs ou joueurs existants serait totalement involontaire.</p>

		</div>


	</footer>



</body>

</html>