
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave" rel="stylesheet">
	
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="flexslider/flexslider.css" type="text/css">
	<script src="flexslider/jquery.flexslider.js"></script>


	<title>Les Loups de Sakami</title>
</head>

<body>

	<header>
		
		<div class="bandeau">

			<a href='./'><img id="logo" src="./images/V4.svg" alt="logo">
			<h1 class="titreLogo">#LesLoupsDeSakami</h1></a>

		</div>
			
		<nav class="menuNav">


			<a href="?page=news">News</a>
			<a href="?page=tickets">Billetterie</a>
			<a href="?page=shop">Boutique</a>
			<a href="?page=team">Équipe</a>
			<a href="?page=school">École de Hockey</a>
			<a href="?page=contact">Contact</a>
			<?php
				if (!isset($_SESSION['id'])) {
				
					echo "<a href='?page=fanzone'>Fan Zone</a>";

				} else {

					echo "<p>Connecté</p>";

				}
			?>

		</nav>

		<div>

			<i class="fas fa-bars"></i>
		
		</div>



		<form class="searchForm">
			
			<label for 
			="search"><i class="fas fa-search"></i></label>
			<input class="searchInput" type="text" name="search" id="search" placeholder="Que recherchez-vous ?">

		</form>


	</header>

	



