

	<main class="container">
	
		<div class="flexslider">
		  <ul class="slides">
		    <li>
		      <a href="#"><div class="caseTitreSlider"><p>Résultats, réactions : les dernières infos des Loups</p></div><img src="images/slider/1.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Réservez vos billets pour le prochain match</p></div><img src="images/slider/2.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Boutique</p></div><img src="images/slider/3.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Effectif : découvrez le "roster" des Loups</p></div><img src="images/slider/4.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Ecole de hockey sur glace</p></div>
		      <img src="images/slider/5.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Nous contacter</p></div>
		      <img src="images/slider/6.jpg" alt="Sakami"/>
		    </li>

		  </ul>
		</div>



	</main>
	
		<script>
	  		$(window).on('load', function() {
	    		$('.flexslider').flexslider();
	  		});
		</script>

</body>
