
	<main class="container">
	
		<div class="flexslider">
		  <ul class="slides">
		    <li>
		      <a href="?page=news"><div class="caseTitreSlider"><p>Résultats, réactions : les dernières infos des Loups</p></div><img src="images/slider/1.png" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Réservez vos billets pour le prochain match</p></div><img src="images/slider/2.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Boutique : portez les couleurs des Loups</p></div><img src="images/slider/3.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="?page=team"><div class="caseTitreSlider"><p>Effectif : découvrez le "roster" des Loups</p></div><img src="images/slider/4.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Ecole de hockey sur glace</p></div>
		      <img src="images/slider/5.jpg" alt="Sakami"/></a>
		    </li>
		    <li><a href="#"><div class="caseTitreSlider"><p>Nous contacter</p></div>
		      <img src="images/slider/6.jpg" alt="Sakami"/>
		    </li>

		  </ul>
		</div>



		<section class="headNews">

			<h1>À la une</h1>

			<article id="lastNews">

				<div class="divRight">
					<a href="?page=article&id=<?=$headNews['id']?>">
					<h2><?= $headNews['title'] ?></h2>
					<p><?= $headNews['subtitle'] ?></p>
				</div>

				<img src="<?= $headNews['picture'] ?>">
					
					</a>

				<div class="clearBoth"></div>
				<a class="toNews" href="?page=news"><i class="fas fa-newspaper"></i>  Voir toutes les news</a>

			</article>

			<article >
				
				<h1>Prochain match</h1>

				<a href="?page=tickets" id="nextGame">
					
					<img id="logo1NextGame" src="./images/V4.svg">
					<p>vs</p>
					<i id="logo2NextGame" class=" fab fa-pied-piper-alt"></i>
					</a>




			</article>


		</section>


	</main>
	
		<script>
	  		$(window).on('load', function() {
	    		$('.flexslider').flexslider();
	  		});
		</script>

</body>

