<main>

	<div class="login">

		<h2>Déjà membre ? Connectez-vous :</h2>

		<form action="?page=login" method="post" id="seconnecter">
			<input type="txt" name="email" placeholder="E-mail ou Pseudo">
			<input type="password" name="password" placeholder="Mot de passe">
			<button type="submit">Se connecter</button>

		</form>


	</div>

	
		
		
		<form class="signin" action="?page=signin" method="post" onsubmit="return checkForm()">

			<h2>Pas encore de compte ? Rejoignez le club </h2>

			<fieldset>

				<legend>Infos personnelles</legend>

				<ul>
				
					<li>

						<label for="firstname">Prénom : </label>
						<input type="text" name="firstname" id="firstname" onblur="checkPrenom(this)">
						<span class="champErreur" id="erreurPrenom"></span>

					</li>

					<li>

						<label for="lastname">Nom : </label>
						<input type="text" name="lastname" id="lastname" onblur="checkNom(this)">
						<span class="champErreur" id="erreurNom"></span>
					
					</li>

					<li>

						<label for="email">Email : </label>
						<input type="text" name="email" id="email" onblur="checkPrenom(this)">
						<span class="champErreur" id="erreurEmail"></span>

					</li>

					<li>
						
						<label for="birthdate">Date de naissance : </label>
						<input type="Date" name="birthdate" id="birthdate" onblur="checkDate(this)">
						<span class="champErreur" id="erreurDate"></span>


					</li>

					<li>

						<label for="address">Adresse : </label>
						<input type="text" name="address" id="address" onblur="checkAddress(this)">
						<span class="champErreur" id="erreurAdresse"></span>


					</li>

					<li>
						<label for="zipCode">Code postal : </label>
						<input type="text" name="zipCode" id="zipCode" onblur="checkPostalCode(this)">
						<span class="champErreur" id="erreurCodePostal"></span>

					</li>

					<li>

						<label for="city">Ville : </label>
						<input type="text" name="city" id="city">
						<span class="champErreur" id="erreurVille"></span>


					</li>


					<li>

						<label for="phone">Téléphone (sans espaces) : </label>
						<input type="text" name="phone" id="phone">
						<span class="champErreur" id="erreurVille"></span>


					</li>


				</ul>



			</fieldset>

			<fieldset>

				<legend>Infos de connexion</legend>

					<ul>

						<li>
							<label for="pseudo">Pseudo : </label>
							<input type="text" name="pseudo" id="pseudo">
						</li>

						<li>
							<label for="password">Mot de passe : </label>
							<input type="password" name="password" id="password">
						</li>
							

					</ul>



				</fieldset>

				<div class="signinbuttons">

					<input id="buttonsubmit" type="submit" value="Envoyer" onclick="checkForm()"></input>

					<input class="buttons" type="reset"></input>

				</div>


		</form>

	</main>


	<footer>
		

	</footer>


    <script type="text/javascript" src="js/form.js"></script>

</body>
