
	<main class="container">

		<div id="titleTeam">
			<h1><i class="fas fa-users"></i> L'équipe</h1>
		</div>

		<section class="sectionEffectif">

			<?php foreach ($players as $player): ?>

				<article class="playerCard"> 

					<a href="?page=player&id=<?= $player['id'] ?>"><img class="playerPicture" src="<?= $player['picture']; ?>" alt="joueur" >
					
						<div class="playerCardBottom">

							<h2 class="h2Player"><?= $player['firstname'].' '.$player['lastname']; ?></h2>

							<h3 class="h3Player"><?= $player['position'] ?></h3>

					
						</div>

					</a>


				</article>


			<?php endforeach; ?>

		</section>




	</main>

</body>


